spring:
  basePackage: app
  datasource:
    jdbc-url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate # Это нужно для того, чтобы Hibernate не выполнял никаких действий по модификации схемы, т.к. теперь их будет делать Liquibase.

hibernate:
  jdbc:
    lob:
      non_contextual_creation: true
  properties:
    dialect: org.hibernate.dialect.PostgreSQL95Dialect
    showSQL: true
    formatSQL: true
