spring:
  basePackage: app
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/test
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate # Это нужно для того, чтобы Hibernate не выполнял никаких действий по модификации схемы, т.к. теперь их будет делать Liquibase.

hibernate:
  jdbc:
    lob:
      non_contextual_creation: true
  properties:
    dialect: org.hibernate.dialect.PostgreSQL95Dialect
    showSQL: true
    formatSQL: true
